git_protocol: https
editor: /usr/bin/nvim
prompt: enabled
pager: less
aliases:
    co: pr checkout
    rv: '!gh repo view "$@" 2>/dev/null || echo "no .git in sight"'
    rvw: '!gh repo view "$@" --web 2>/dev/null || echo "no .git in sight"'
http_unix_socket:
browser: "/mnt/c/PROGRA~1/BraveSoftware/Brave-Browser/Application/brave.exe"
version: "1"
